package com.example.practicarlogin.piezas

class ListaPiezas {
    companion object {
        val procesadores = listOf(
            CPU(
                "Ryzen 9 7950X3D",
                "AMD",
                "AM5",
                16,
                32,
                699.99,
                4.2,
                "No disponible",
                170.0,
                "5nm",
                "https://file1.hkepc.net/2023/02/source/24202242-6b03f190af726e006a5b82b.jpg"
            ),
            CPU(
                "Ryzen 7 7800X3D",
                "AMD",
                "AM5",
                8,
                16,
                449.99,
                4.2,
                "No disponible",
                120.0,
                "5nm",
                "https://plecom.imgix.net/iil-332627-657776.jpg?fit=fillmax&fill=solid&fill-color=ffffff&auto=format&w=1000&h=1000"
            ),
            CPU(
                "Ryzen 5 7600X",
                "AMD",
                "AM5",
                6,
                12,
                299.99,
                4.7,
                "Radeon Vega 7",
                105.0,
                "5nm",
                "https://www.tmt.my/data/editor/product/CPU-AMDR57600/Ryzen7000Series.jpg"
            ),
            CPU(
                "Intel Core i9-13900K",
                "Intel",
                "LGA1700",
                24,
                32,
                599.99,
                3.0,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://th.bing.com/th/id/OIP.Zm-SHr4HucA4H-Q5FDp0AQHaHa?rs=1&pid=ImgDetMain"
            ),
            CPU(
                "Intel Core i7-13700K",
                "Intel",
                "LGA1700",
                16,
                24,
                419.99,
                3.4,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://www.nexxcom.lk/wp-content/uploads/2022/10/INTEL%C2%AE-CORE%E2%84%A2-i7-13700K-PROCESSOR-copy-min.png"
            ),
            CPU(
                "Intel Core i5-13600K",
                "Intel",
                "LGA1700",
                14,
                20,
                319.99,
                3.5,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://staticg.sportskeeda.com/editor/2022/09/64f29-16644703278615-1920.jpg"
            ),
            CPU(
                "Ryzen 9 5950X",
                "AMD",
                "AM4",
                16,
                32,
                549.99,
                3.4,
                "No disponible",
                105.0,
                "7nm",
                "https://brain-images-ssl.cdn.dixons.com/8/8/10216688/u_10216688.jpg"
            ),
            CPU(
                "Ryzen 7 5700G",
                "AMD",
                "AM4",
                8,
                16,
                359.99,
                3.8,
                "Radeon Vega 8",
                65.0,
                "7nm",
                "https://dp-distribution.com/wp-content/uploads/2023/01/Ryzen-5-5700G.jpg"
            ),
            CPU(
                "Intel Core i9-12900K",
                "Intel",
                "LGA1700",
                16,
                24,
                589.99,
                3.2,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://th.bing.com/th/id/R.05e4924be5d9b422f14e1249cafb33e7?rik=oCkWemrqay6gGw&riu=http%3a%2f%2fultragearcomputer.com%2fmedia%2fcatalog%2fproduct%2fcache%2fbcc7265378a03f7e694c8e8cc0e70edb%2f1%2f2%2f12900k.jpg&ehk=xTxhhTh57hOBwZ3HGbPQhYxF8jv%2bDd%2f88gr93%2fgeNSg%3d&risl=&pid=ImgRaw&r=0"
            ),
            CPU(
                "Intel Core i7-12700K",
                "Intel",
                "LGA1700",
                12,
                20,
                409.99,
                3.6,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://th.bing.com/th/id/OIP.QC8HCvNuEdSjSEdWqhLFYAHaIA?rs=1&pid=ImgDetMain"
            ),
            CPU(
                "Intel Core i5-12600K",
                "Intel",
                "LGA1700",
                10,
                16,
                289.99,
                3.7,
                "Intel UHD Graphics 770",
                125.0,
                "10nm",
                "https://processeur.org/wp-content/uploads/2022/09/71Ahm5CD6XL._AC_SL1500_.jpg"
            ),
            CPU(
                "Ryzen 5 5600G",
                "AMD",
                "AM4",
                6,
                12,
                229.99,
                3.9,
                "Radeon Vega 7",
                65.0,
                "7nm",
                "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKs1w18ke4irI1rReAK1hmPmsgt499L7dH5VVDGV8uAxl2ZELFzAKSQZIQRL2lTP74HEPTtiqG2uP0Gv_IZeHX9c9lMSK_qMJfXiGYvqivFEyrJ3TDt_f2A53RWD1x8p4uj7KuhVHjDHCzlZxS27HX080NQUtgcAubA3ppT_NneWte2uOS8MW_q-xr/w1200-h630-p-k-no-nu/70.png"
            ),
            CPU(
                "Ryzen 9 7900",
                "AMD",
                "AM5",
                12,
                24,
                429.99,
                3.7,
                "Radeon Vega 7",
                65.0,
                "5nm",
                "https://www.bhphotovideo.com/images/images1000x1000/amd_100_100000590box_ryzen_9_7900_12_core_1741653.jpg"
            ),
            CPU(
                "Intel Core i5-13400",
                "Intel",
                "LGA1700",
                10,
                16,
                225.99,
                2.5,
                "Intel UHD Graphics 730",
                65.0,
                "10nm",
                "https://th.bing.com/th/id/OIP.AVp6SYBIn9enybV-mGeYLQHaFj?rs=1&pid=ImgDetMain"
            ),
            CPU(
                "Ryzen 7 7700",
                "AMD",
                "AM5",
                8,
                16,
                329.99,
                3.8,
                "Radeon Vega 8",
                65.0,
                "5nm",
                "https://www.bhphotovideo.com/images/images1000x1000/amd_100_100000592box_ryzen_7_7700_eight_core_1741654.jpg"),
            CPU(
                "Intel Core i3-12100",
                "Intel",
                "LGA1700",
                4,
                8,
                129.99,
                3.3,
                "Intel UHD Graphics 730",
                60.0,
                "10nm",
                "https://m.media-amazon.com/images/S/aplus-media-library-service-media/1ed1574e-4d09-49bc-b219-1b264010a839.__CR0,0,970,600_PT0_SX970_V1___.jpg"
            ),
            CPU("Ryzen 3 5300G",
                "AMD",
                "AM4",
                4, 8,
                129.99,
                4.0,
                "Radeon Vega 6",
                65.0,
                "7nm",
                "https://www.tiendaclic.com.ar/81325721-thickbox_default/procesador-amd-ryzen-3-5300-g-4-0-ghz-am-4-4-nucleos.jpg"),
            CPU(
                "Intel Core i3-10105",
                "Intel",
                "LGA1200",
                4,
                8,
                104.99,
                3.7,
                "Intel UHD Graphics 630",
                65.0,
                "14nm",
                "https://th.bing.com/th/id/R.d4ab5c0a334551efb7b1a5b96877d63d?rik=%2fvMRLL%2fHT45ZUg&pid=ImgRaw&r=0"
            ),
            CPU(
                "Ryzen 5 3400G",
                "AMD",
                "AM4",
                4,
                8,
                149.99,
                3.7,
                "Radeon Vega 11",
                65.0,
                "12nm",
                "https://images-na.ssl-images-amazon.com/images/I/31SW%2BKVa%2BML.jpg"
            ),
            CPU(
                "Intel Pentium Gold G7400",
                "Intel",
                "LGA1700",
                2,
                4,
                64.99,
                3.7,
                "Intel UHD Graphics 710",
                46.0,
                "10nm",
                "https://hanoicomputercdn.com/media/product/64780_cpu_intel_pentium_gold_g7400.jpg"
            )
        )

        val boards = listOf(
            Board(
                nombre = "ASUS Prime X370-Pro",
                marca = "ASUS",
                socket = "AM4",
                tipoMemoria = "DDR4",
                chipset = "X370",
                cantidadUSB = "6",
                slotsRam = 4,
                factorForma = "ATX",
                puertosSata = 6,
                puertosM2 = 2,
                permiteAPU = true,
                urlImagen = "https://dlcdnimgs.asus.com/websites/global/products/s7csF4UqmJykbmtW/images/kv/main_kv.jpg"
            ),
            Board(
                nombre = "Gigabyte GA-AB350-Gaming 3",
                marca = "Gigabyte",
                socket = "AM4",
                tipoMemoria = "DDR4",
                chipset = "B350",
                cantidadUSB = "8",
                slotsRam = 4,
                factorForma = "ATX",
                puertosSata = 6,
                puertosM2 = 1,
                permiteAPU = true,
                urlImagen = "https://static.gigabyte.com/StaticFile/Image/Global/323899f1daacee9614d98d972634de10/Product/16801/Png"
            ),
            Board(
                nombre = "MSI X470 Gaming Plus",
                marca = "MSI",
                socket = "AM4",
                tipoMemoria = "DDR4",
                chipset = "X470",
                cantidadUSB = "10",
                slotsRam = 4,
                factorForma = "ATX",
                puertosSata = 6,
                puertosM2 = 2,
                permiteAPU = true,
                urlImagen = "https://asset.msi.com/global/picture/features/MB/Gaming/X470/msi-x470-gaming-plus-cooling01.jpg"
            ),
            Board(
                nombre = "ASRock B450M Steel Legend",
                marca = "ASRock",
                socket = "AM4",
                tipoMemoria = "DDR4",
                chipset = "B450",
                cantidadUSB = "8",
                slotsRam = 4,
                factorForma = "Micro-ATX",
                puertosSata = 4,
                puertosM2 = 2,
                permiteAPU = true,
                urlImagen = "https://www.asrock.com/mb/features/POLYRGBLED-B450M%20Steel%20Legend_mobile.fr.jpg"
            ),
            Board(
                nombre = "Biostar Racing X570GT8",
                marca = "Biostar",
                socket = "AM4",
                tipoMemoria = "DDR4",
                chipset = "X570",
                cantidadUSB = "10",
                slotsRam = 4,
                factorForma = "Mini-ITX",
                puertosSata = 4,
                puertosM2 = 1,
                permiteAPU = true,
                urlImagen = "https://pics.computerbase.de/8/7/7/1/0/1-1080.eea20f53.jpg"
            ),
            Board(
                nombre = "ASUS ROG Strix Z370-E Gaming",
                marca = "ASUS",
                socket = "LGA 1151",
                tipoMemoria = "DDR4",
                chipset = "Z370",
                cantidadUSB = "8",
                slotsRam = 4,
                factorForma = "ATX",
                puertosSata = 6,
                puertosM2 = 2,
                permiteAPU = false,
                urlImagen = "https://pics.computerbase.de/8/7/7/1/0/1-1080.eea20f53.jpg"
            ),
            Board(
                nombre = "Gigabyte B360M DS3H",
                marca = "Gigabyte",
                socket = "LGA 1151",
                tipoMemoria = "DDR4",
                chipset = "B360",
                cantidadUSB = "6",
                slotsRam = 4,
                factorForma = "ATX",
                puertosSata = 6,
                puertosM2 = 1,
                permiteAPU = false,
                urlImagen = "https://static.gigabyte.com/StaticFile/Image/Global/e02469ef0d3c79510e1bd96a5815c368/Product/19418/Png"
            ),
            Board(
                nombre = "MSI H370 Gaming Pro Carbon",
                marca = "MSI",
                socket = "LGA 1151",
                tipoMemoria = "DDR4",
                chipset = "H370",
                cantidadUSB = "8",
                slotsRam = 4,
                factorForma = "Micro-ATX",
                puertosSata = 4,
                puertosM2 = 2,
                permiteAPU = false,
                urlImagen = "https://asset.msi.com/global/picture/features/MB/Gaming/H370/h370_gaming_pro_carbon_cooling_3840.jpg"
            )
        )


    }
}